# Generated by Django 2.0 on 2018-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='main_page',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
    ]
