# Generated by Django 2.0 on 2018-06-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_main_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimages',
            options={'ordering': ['is_main'], 'verbose_name': 'Фото проекта', 'verbose_name_plural': 'Фото проектов'},
        ),
    ]
