# Generated by Django 2.0 on 2018-06-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180613_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='works',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Выполненные работы'),
        ),
    ]
