# Generated by Django 2.0.6 on 2018-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
