# Generated by Django 2.0 on 2018-06-13 02:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_services_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSubcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Название')),
                ('content', tinymce.models.HTMLField(default=None, verbose_name='Контент на детальной странице')),
                ('cateory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prices.ServicesCategories')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='categorie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prices.ServicesSubcategories'),
        ),
    ]
