# Generated by Django 2.0 on 2018-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_auto_20180613_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='v',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Единицы измерения (м2)'),
        ),
    ]
