# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_auto_20180619_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesfork',
            name='calcprice',
            field=models.IntegerField(default=0, verbose_name='Цена для калькулятора'),
        ),
    ]
