# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-23 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0010_services_remonttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='remonttype',
        ),
        migrations.AddField(
            model_name='services',
            name='remonttype',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='prices.PricesFork', verbose_name='Тип ремонта'),
        ),
    ]
