# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0011_auto_20180623_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='remonttype',
            field=models.ManyToManyField(blank=True, default=None, to='prices.PricesFork', verbose_name='Тип ремонта'),
        ),
    ]
