# Generated by Django 2.0 on 2018-06-09 09:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_img', models.ImageField(upload_to='static/img', verbose_name='Иконка в заголовке')),
                ('title', tinymce.models.HTMLField(default=None, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(default=None, verbose_name='Текст')),
                ('button_text', models.TextField(blank=True, default=None, max_length=556, null=True, verbose_name='Текст на кнопке')),
                ('href', models.TextField(blank=True, default=None, max_length=556, null=True, verbose_name='Ссылка (если попап - оставить поле пустым)')),
                ('background', models.ImageField(upload_to='static/img/main', verbose_name='Фоновая картинка')),
            ],
        ),
    ]
