# Generated by Django 2.0 on 2018-06-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidermain',
            options={'verbose_name': 'Слайд первого экрана', 'verbose_name_plural': 'Слайды первого экрана'},
        ),
    ]
