# Generated by Django 2.0 on 2018-06-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180609_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermain',
            name='button_text',
            field=models.CharField(blank=True, default=None, max_length=556, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='href',
            field=models.CharField(blank=True, default=None, max_length=556, null=True, verbose_name='Ссылка (если попап - оставить поле пустым)'),
        ),
    ]
