# Generated by Django 2.0 on 2018-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180609_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermain',
            name='title_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img', verbose_name='Иконка в заголовке'),
        ),
    ]
