# Generated by Django 2.0 on 2018-06-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180609_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block1Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Заголовок')),
                ('price', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Цена')),
                ('terms', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Сроки')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='static/img/block1', verbose_name='Фоновая картинка')),
                ('href', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
            },
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='button_text',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='href',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Ссылка (если попап - оставить поле пустым)'),
        ),
    ]
