# Generated by Django 2.0 on 2018-06-09 10:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180609_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block3Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Заголовок')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='static/img/block3', verbose_name='Фоновая картинка')),
            ],
            options={
                'verbose_name': 'Блок 3 - ремонт квартир',
                'verbose_name_plural': 'Элемент',
            },
        ),
        migrations.CreateModel(
            name='Block3MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(default=None, verbose_name='Пункт элемента')),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Block3Main')),
            ],
            options={
                'verbose_name': 'Пункт элемента',
                'verbose_name_plural': 'Пункты элемента',
            },
        ),
    ]
