# Generated by Django 2.0 on 2018-06-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_block3main_block3maintext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block3main',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Блок 3 - ремонт квартир'},
        ),
    ]
