# Generated by Django 2.0 on 2018-06-09 10:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180609_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', tinymce.models.HTMLField(default=None, verbose_name='Заголовок 1')),
                ('title2', tinymce.models.HTMLField(default=None, verbose_name='Заголовок 2')),
                ('text', tinymce.models.HTMLField(default=None, verbose_name='Текст')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='static/img/block9', verbose_name='Фоновая картинка')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции и скидки',
            },
        ),
    ]
