# Generated by Django 2.0 on 2018-06-12 08:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20180612_1839'),
        ('main', '0008_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField(default=None, verbose_name='Вопрос')),
                ('answer', tinymce.models.HTMLField(default=None, verbose_name='Ответ')),
                ('person', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.Stuff')),
            ],
            options={
                'verbose_name': 'Вопрос - Ответ',
                'verbose_name_plural': 'Вопрос - Ответ',
            },
        ),
    ]
