# Generated by Django 2.0 on 2018-06-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block1Main',
        ),
    ]
