# Generated by Django 2.0 on 2018-06-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20180612_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howwedo',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Как мы работаем'},
        ),
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
    ]
