# Generated by Django 2.0 on 2018-06-12 10:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20180612_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='static/img/replies/', verbose_name='Фото')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Имя')),
                ('age', models.IntegerField(blank=True, default=None, null=True, verbose_name='Возраст')),
                ('address', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Адрес')),
                ('text', tinymce.models.HTMLField(default=None, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
            },
        ),
    ]
