# Generated by Django 2.0 on 2018-06-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_replies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
