# Generated by Django 2.0 on 2018-06-13 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page2',
            name='menu',
        ),
        migrations.AddField(
            model_name='page2',
            name='page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Page', verbose_name='Страница родительская'),
        ),
    ]
