# Generated by Django 2.0.6 on 2018-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180614_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='page2',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
