# Generated by Django 2.0.6 on 2018-07-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180619_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page2',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Заголовок'),
        ),
    ]
