# Generated by Django 2.0.6 on 2018-07-07 13:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180705_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='menubullet',
            name='content',
            field=tinymce.models.HTMLField(default=None, verbose_name='Контент на детальной странице'),
        ),
        migrations.AddField(
            model_name='menubullet',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='menubullet',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='URL страницы'),
        ),
        migrations.AddField(
            model_name='menubullet',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Заголовок'),
        ),
    ]
